# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pixeltalk Leipzig
description: Ein offenes Meetup zu allen Webthemen in Leipzig.
introtext: >- # this means to ignore newlines until "baseurl:"
    Von der Konzeption über die Gestaltung bis hin zur
    technischen Umsetzung und darüber hinaus. Jeden letzten
    Mittwoch im Monat.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pixeltalk.io" # the base hostname & protocol for your site, e.g. http://example.com
url_subnav_signal: "https://signal.group/#CjQKIDbTfUYmRkmbXcUgmYd4pkv1EOSoT416FxAkJy60yZrJEhCaTd-P8J5Xd8WxQVEF-vxn"
url_subnav_github: "https://github.com/Pixeltalk-Leipzig/website/discussions"
url_subnav_linkedin: "https://www.linkedin.com/events/pixeltalk10-kirbymeetup7316730229593436160/"
url_subnav_betterplace: "https://www.betterplace.me/pixeltalk-leipzig"

date_idx: 10
date_next: Mi 30.4. 19:00
date_place: Unite
date_place_url: https://maps.app.goo.gl/dPAFC27gGBMKcBbL7?g_st=ac
date_title: Pixeltalk × Kirby Meetup
date_desc: Die 10. Ausgabe des Pixeltalks. Diesmal zusammen mit dem Kirby Meetup Leipzig. Es gibt einen kleinen Impulsvortrag von <a href="https://webgefrickel.de" target="_blank" class="underline">Steffen</a> zusammen mit Einblicken von <a href="https://www.scheinundsein.de" target="_blank" class="underline">Anne</a> und <a href="https://www.falk-m.de" target="_blank" class="underline">Falk</a> zu <a href="https://getkirby.com" target="_blank" class="underline">Kirby CMS</a>.

collections:
  meetups:

# Build settings
# theme: minima
# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
